[package]
name = "myprofiler"
version = "0.1.0"
authors = ["Hideo Hattori <hattori-h@klab.com>"]

[dependencies]
mysql = "*"
getopts = "0.2.4"
users = "0.5.0"
time = "0.1"
regex = "0.1"

[dependencies.lazy_static]
git = "https://github.com/rust-lang-nursery/lazy-static.rs"
